cookbook 'snmp'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'mongodb'
cookbook 'haproxy'
cookbook 'unicorn'
cookbook 'rsyslog'
#cookbook 'zenoss', git: 'git@github.com:opscode-cookbooks/zenoss.git'
cookbook 'zenoss', git: 'git@github.com:krogebry/zenoss.git'
cookbook 'elasticsearch'

cookbook 'bakery', path: '/home/krogebry/dev/bakery/cookbooks/bakery'
cookbook 'slb_pie', path: '/home/krogebry/dev/bakery/cookbooks/slb_pie'
cookbook 'web_pie', path: '/home/krogebry/dev/bakery/cookbooks/web_pie'
cookbook 'log_pie', path: '/home/krogebry/dev/bakery/cookbooks/log_pie'
