cookbook 'snmp'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'mongodb'
cookbook 'haproxy'
cookbook 'unicorn'
cookbook 'rsyslog'
cookbook 'zenoss', git: 'git@github.com:opscode-cookbooks/zenoss.git'

#cookbook 'bakery', git: 'git@github.com:krogebry/bakery.git'
#cookbook 'slb_pie', git: 'git@github.com:krogebry/web_pie.git'
#cookbook 'web_pie', git: 'git@github.com:krogebry/slb_pie.git'
